users_list = [
    {"name": "Marek", "nick":"mj", "posts":5},
    {"name":"Mateusz", "św":"Bartosz", "posts":7},
    {"name":"Bartosz", "nick":"Br", "posts":10},
    {"name":"Kamil", "nick":"ko", "posts":11},
    {"name":"Monika", "nick":"Bartosz", "posts":12},
    {"name":"Wiktoria", "nick":"Bartosz", "posts":13},
    {"name":"Karol", "nick":"Bartosz", "posts":14},
    {"name":"Tomasz", "nick":"Bartosz", "posts":14}],
    {"name":"Agata", "nick":"Bartosz", "posts":14}],